### ISSUE TITLE
The supertask 'text-to-text' does not correspond to a Hugging Face AutoModel type (such as `AutoModelForSequenceClassification`).

### ISSUE THREAD

**Issue by timpal0l** [ScandEval/ScandEval#141]
It makes sense that a BERT Encoder shall not handle text-to-text tasks. Shall the framework not skip this task then for that architecture, if its not a T5 model or Bart, for e.g.

```bash
pip uninstall -y scandeval && pip install git+https://github.com/ScandEval/ScandEval@feat/use-vllm && CUDA_VISIBLE_DEVICES=0 scandeval -m AI-Sweden-Models/bert-large-nordic-pile-1M-steps --raise-errors --verbose
```
```python
2024-01-10 23:24:09 ⋅ Benchmarking AI-Sweden-Models/bert-large-nordic-pile-1M-steps on the truncated version of Nordjylland News
Traceback (most recent call last):
  File "/home/nlu/anaconda3/envs/scandeval/bin/scandeval", line 8, in <module>
    sys.exit(benchmark())
             ^^^^^^^^^^^
  File "/home/nlu/anaconda3/envs/scandeval/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nlu/anaconda3/envs/scandeval/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/nlu/anaconda3/envs/scandeval/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nlu/anaconda3/envs/scandeval/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nlu/anaconda3/envs/scandeval/lib/python3.11/site-packages/scandeval/cli.py", line 268, in benchmark
    benchmarker(model_id=model_ids, dataset=datasets)
  File "/home/nlu/anaconda3/envs/scandeval/lib/python3.11/site-packages/scandeval/benchmarker.py", line 481, in __call__
    return self.benchmark(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nlu/anaconda3/envs/scandeval/lib/python3.11/site-packages/scandeval/benchmarker.py", line 293, in benchmark
    record = self._benchmark_single(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nlu/anaconda3/envs/scandeval/lib/python3.11/site-packages/scandeval/benchmarker.py", line 476, in _benchmark_single
    raise e
  File "/home/nlu/anaconda3/envs/scandeval/lib/python3.11/site-packages/scandeval/benchmarker.py", line 433, in _benchmark_single
    results, metadata_dict = dataset(model_id)
                             ^^^^^^^^^^^^^^^^^
  File "/home/nlu/anaconda3/envs/scandeval/lib/python3.11/site-packages/scandeval/benchmark_dataset.py", line 507, in __call__
    return self.benchmark(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nlu/anaconda3/envs/scandeval/lib/python3.11/site-packages/scandeval/benchmark_dataset.py", line 119, in benchmark
    tokenizer, model = load_model(
                       ^^^^^^^^^^^
  File "/home/nlu/anaconda3/envs/scandeval/lib/python3.11/site-packages/scandeval/model_loading.py", line 50, in load_model
    tokenizer, model = setup.load_model(
                       ^^^^^^^^^^^^^^^^^
  File "/home/nlu/anaconda3/envs/scandeval/lib/python3.11/site-packages/scandeval/model_setups/hf.py", line 296, in load_model
    raise InvalidBenchmark(
scandeval.exceptions.InvalidBenchmark: The supertask 'text-to-text' does not correspond to a Hugging Face AutoModel type (such as `AutoModelForSequenceClassification`).
```
```bash
(scandeval) nlu@4a607c110ef7:~/working_dir$ pip list
Package                   Version
------------------------- ------------
absl-py                   2.0.0
accelerate                0.25.0
aiohttp                   3.9.1
aioprometheus             23.12.0
aiosignal                 1.3.1
anyio                     4.2.0
argcomplete               3.2.1
asttokens                 2.4.1
attrs                     23.2.0
bert-score                0.3.13
bitsandbytes              0.42.0
Brotli                    1.0.9
certifi                   2023.11.17
cffi                      1.16.0
charset-normalizer        2.0.4
chex                      0.1.85
click                     8.1.7
contourpy                 1.2.0
cryptography              41.0.7
cycler                    0.12.1
datasets                  2.16.1
decorator                 5.1.1
demjson3                  3.0.6
dill                      0.3.7
einops                    0.7.0
etils                     1.6.0
evaluate                  0.4.1
executing                 2.0.1
fastapi                   0.108.0
filelock                  3.13.1
flash-attn                2.4.2
flax                      0.7.5
fonttools                 4.47.0
frozenlist                1.4.1
fsspec                    2023.10.0
gmpy2                     2.1.2
h11                       0.14.0
httptools                 0.6.1
huggingface-hub           0.20.2
idna                      3.4
importlib-resources       6.1.1
ipython                   8.20.0
jax                       0.4.23
jaxlib                    0.4.23
jedi                      0.19.1
Jinja2                    3.1.2
joblib                    1.3.2
jsonschema                4.20.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
Levenshtein               0.23.0
markdown-it-py            3.0.0
MarkupSafe                2.1.3
matplotlib                3.8.2
matplotlib-inline         0.1.6
mdurl                     0.1.2
mkl-fft                   1.3.8
mkl-random                1.2.4
mkl-service               2.4.0
ml-dtypes                 0.3.2
mpmath                    1.3.0
msgpack                   1.0.7
multidict                 6.0.4
multiprocess              0.70.15
nest-asyncio              1.5.8
networkx                  3.1
ninja                     1.11.1.1
nltk                      3.8.1
numpy                     1.26.3
openai                    0.28.1
opt-einsum                3.3.0
optax                     0.1.7
orbax-checkpoint          0.4.8
orjson                    3.9.10
packaging                 23.2
pandas                    1.5.3
parso                     0.8.3
pexpect                   4.9.0
Pillow                    10.0.1
pip                       23.3.1
pipx                      1.4.1
platformdirs              4.1.0
prompt-toolkit            3.0.43
protobuf                  3.20.3
psutil                    5.9.7
ptyprocess                0.7.0
pure-eval                 0.2.2
pyarrow                   14.0.2
pyarrow-hotfix            0.6
pycparser                 2.21
pydantic                  1.10.13
Pygments                  2.17.2
pyinfer                   0.0.3
pyOpenSSL                 23.2.0
pyparsing                 3.1.1
PySocks                   1.7.1
python-dateutil           2.8.2
python-dotenv             0.21.1
pytz                      2023.3.post1
PyYAML                    6.0.1
quantile-python           1.1
rapidfuzz                 3.6.1
ray                       2.9.0
referencing               0.32.1
regex                     2023.12.25
requests                  2.31.0
responses                 0.18.0
rich                      13.7.0
rouge-score               0.1.2
rpds-py                   0.16.2
sacremoses                0.1.1
safetensors               0.4.1
ScandEval                 8.2.1
scikit-learn              1.3.2
scipy                     1.11.4
sentencepiece             0.1.99
seqeval                   1.2.2
setuptools                68.2.2
six                       1.16.0
sniffio                   1.3.0
stack-data                0.6.3
starlette                 0.32.0.post1
sympy                     1.12
tabulate                  0.9.0
tensorstore               0.1.52
termcolor                 2.4.0
threadpoolctl             3.2.0
tiktoken                  0.5.2
tokenizers                0.15.0
toolz                     0.12.0
torch                     2.1.2
torchaudio                2.1.2
torchvision               0.16.2
tqdm                      4.66.1
traitlets                 5.14.1
transformers              4.36.2
triton                    2.1.0
typing_extensions         4.9.0
urllib3                   1.26.18
userpath                  1.9.1
uvicorn                   0.25.0
uvloop                    0.19.0
vllm                      0.2.7
watchfiles                0.21.0
wcwidth                   0.2.13
websockets                12.0
wheel                     0.41.2
xformers                  0.0.23.post1
xxhash                    3.4.1
yarl                      1.9.4
zipp                      3.17.0
```

**Comment by saattrupdan** [comment]
It will simply skip it if `--raise-errors` is not set - that flag is mainly used for debugging 🙂

But the error message could be more informative for sure - noted!
