### ISSUE TITLE
[BUG] SUC3 overflow

### ISSUE THREAD

**Issue by saattrupdan** [ScandEval/ScandEval#193]
**Describe the bug**
The model `peter-sk/gpt-neox-da` bugs when benchmarking on SUC 3.0. Here's a traceback:

```
2024-01-25 12:57:01 ⋅ Benchmarking peter-sk/gpt-neox-da on the truncated version of SUC 3.0
2024-01-25 12:57:04 ⋅ Loading model and tokenizer...
Traceback (most recent call last):
  File "/home/ubuntu/.venv/bin/scandeval", line 8, in <module>
    sys.exit(benchmark())
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/cli.py", line 268, in benchmark
    benchmarker(model_id=model_ids, dataset=datasets)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 485, in __call__
    return self.benchmark(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 300, in benchmark
    record = self._benchmark_single(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 437, in _benchmark_single
    results, metadata_dict = dataset(model_id)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmark_dataset.py", line 526, in __call__
    return self.benchmark(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmark_dataset.py", line 116, in benchmark
    tokenizer, model = load_model(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/model_loading.py", line 50, in load_model
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 485, in __call__                                                                                                                                                                 [11/68]
    return self.benchmark(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 300, in benchmark
    record = self._benchmark_single(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 437, in _benchmark_single
    results, metadata_dict = dataset(model_id)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmark_dataset.py", line 526, in __call__
    return self.benchmark(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmark_dataset.py", line 116, in benchmark
    tokenizer, model = load_model(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/model_loading.py", line 50, in load_model
    tokenizer, model = setup.load_model(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/model_setups/hf.py", line 399, in load_model
    model, tokenizer = align_model_and_tokenizer(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/model_setups/utils.py", line 169, in align_model_and_tokenizer
    model(dummy_inputs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/vllm_models.py", line 266, in __call__
    return self.generate(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/vllm_models.py", line 199, in generate
    raw_outputs = self._model.generate(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 165, in generate
    return self._run_engine(use_tqdm)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/vllm_models.py", line 329, in _run_engine_with_fixed_progress_bars
    step_outputs = self.llm_engine.step()
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 628, in step
    all_outputs = self._run_workers(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 795, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/worker/worker.py", line 189, in execute_model
    output = self.model_runner.execute_model(seq_group_metadata_list,
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 461, in execute_model
    output = self.model.sample(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/model_executor/models/gpt_neox.py", line 259, in sample
    next_tokens = self.sampler(self.embed_out.weight, hidden_states,
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/model_executor/layers/sampler.py", line 59, in forward
    logits = _apply_logits_processors(logits, sampling_metadata)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/model_executor/layers/sampler.py", line 155, in _apply_logits_processors
    logits_row = logits_processor(token_ids, logits_row)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/vllm_models.py", line 301, in no_tabs_or_newlines
    mask[forbidden_token_id] = -1e9
RuntimeError: value cannot be converted to type at::Half without overflow
```

**To Reproduce**
`scandeval -m peter-sk/gpt-neox-da -d suc3`

**Context (please complete the following information):**
 - OS [e.g., MacOS, Ubuntu]: Ubuntu
 - Python version [e.g., 3.10.6]: 3.10.12
 - Device [e.g., CUDA, CPU, MPS]: CUDA
 - Output of `pip list` or `poetry show`: 
 ```
(.venv) ubuntu@man-in-pink:~$ pip list
Package                   Version
------------------------- ------------
absl-py                   2.0.0
accelerate                0.25.0
aiohttp                   3.9.1
aioprometheus             23.12.0
aiosignal                 1.3.1
annotated-types           0.6.0
anyio                     4.2.0
async-timeout             4.0.3
attrs                     23.2.0
bert-score                0.3.13
bitsandbytes              0.41.3.post2
certifi                   2023.11.17
charset-normalizer        3.3.2
chex                      0.1.85
click                     8.1.7
contourpy                 1.2.0
cycler                    0.12.1
datasets                  2.16.1
demjson3                  3.0.6
dill                      0.3.7
einops                    0.7.0
etils                     1.6.0
evaluate                  0.4.1
exceptiongroup            1.2.0
fastapi                   0.109.0
filelock                  3.13.1
flash-attn                2.4.2
flax                      0.7.5
fonttools                 4.47.0
frozenlist                1.4.1
fsspec                    2023.10.0
h11                       0.14.0
httptools                 0.6.1
huggingface-hub           0.20.1
idna                      3.6
importlib-resources       6.1.1
interegular               0.3.3
jax                       0.4.23
jaxlib                    0.4.23
Jinja2                    3.1.2
joblib                    1.3.2
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
Levenshtein               0.23.0
lm-format-enforcer        0.8.2
markdown-it-py            3.0.0
MarkupSafe                2.1.3
matplotlib                3.8.2
mdurl                     0.1.2
ml-dtypes                 0.3.2
mpmath                    1.3.0
msgpack                   1.0.7
multidict                 6.0.4
multiprocess              0.70.15
nest-asyncio              1.5.8
networkx                  3.2.1
ninja                     1.11.1.1
nltk                      3.8.1
numpy                     1.26.3
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.18.1
nvidia-nvjitlink-cu12     12.3.101
nvidia-nvtx-cu12          12.1.105
openai                    0.28.1
opt-einsum                3.3.0
optax                     0.1.7
orbax-checkpoint          0.4.8
orjson                    3.9.12
packaging                 23.2
pandas                    1.5.3
pillow                    10.2.0
pip                       23.3.2
protobuf                  3.20.3
psutil                    5.9.7
pyarrow                   14.0.2
pyarrow-hotfix            0.6
pydantic                  1.10.13
pydantic_core             2.14.6
Pygments                  2.17.2
pyinfer                   0.0.3
pyparsing                 3.1.1
python-dateutil           2.8.2
python-dotenv             0.21.1
pytz                      2023.3.post1
PyYAML                    6.0.1
quantile-python           1.1
rapidfuzz                 3.6.1
ray                       2.9.1
referencing               0.32.1
regex                     2023.12.25
requests                  2.31.0
responses                 0.18.0
rich                      13.7.0
rouge_score               0.1.2
rpds-py                   0.17.1
sacremoses                0.1.1
safetensors               0.4.1
scandeval                 9.2.0
scikit-learn              1.3.2
scipy                     1.11.4
sentencepiece             0.1.99
seqeval                   1.2.2
setuptools                59.6.0
six                       1.16.0
sniffio                   1.3.0
starlette                 0.35.1
sympy                     1.12
tabulate                  0.9.0
tensorstore               0.1.52
termcolor                 2.4.0
threadpoolctl             3.2.0
tiktoken                  0.5.2
tokenizers                0.15.0
toolz                     0.12.0
torch                     2.1.2
tqdm                      4.66.1
transformers              4.36.2
triton                    2.1.0
typing_extensions         4.9.0
urllib3                   2.1.0
uvicorn                   0.27.0
uvloop                    0.19.0
vllm                      0.2.7
watchfiles                0.21.0
websockets                12.0
wheel                     0.42.0
xformers                  0.0.23.post1
xxhash                    3.4.1
yarl                      1.9.4
zipp                      3.17.0
```

**Comment by saattrupdan** [comment]
This also happens with the model `RJuro/kanelsnegl-v0.1`.
