### ISSUE TITLE
[BUG]  Issue loading Yi based model

### ISSUE THREAD

**Issue by mhenrichsen** [ScandEval/ScandEval#268]
### 🐛 Describe the bug

Model loads and runs fine when using vLLM, but fails when using Scandeval. Running on a A100 8GB.

```
mgh@scandeval:~$ scandeval --model mhenrichsen/danskgpt-chat-v3 --language da --only-validation-split --use-token --trust-remote-code --use-flash-attention
2024-02-25 19:50:17 ⋅ Benchmarking mhenrichsen/danskgpt-chat-v3 on the truncated version of the Danish sentiment classification dataset AngryTweets
2024-02-25 19:50:18 ⋅ Loading model and tokenizer...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.74it/s]
Traceback (most recent call last):
  File "/home/mgh/.local/bin/scandeval", line 8, in <module>
    sys.exit(benchmark())
  File "/home/mgh/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/mgh/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mgh/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/scandeval/cli.py", line 281, in benchmark
    benchmarker(model=models)
  File "/home/mgh/.local/lib/python3.10/site-packages/scandeval/benchmarker.py", line 679, in __call__
    return self.benchmark(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/scandeval/benchmarker.py", line 530, in benchmark
    record = self._benchmark_single(
  File "/home/mgh/.local/lib/python3.10/site-packages/scandeval/benchmarker.py", line 631, in _benchmark_single
    results, metadata_dict = dataset(model_id)
  File "/home/mgh/.local/lib/python3.10/site-packages/scandeval/benchmark_dataset.py", line 564, in __call__
    return self.benchmark(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/scandeval/benchmark_dataset.py", line 127, in benchmark
    tokenizer, model = load_model(
  File "/home/mgh/.local/lib/python3.10/site-packages/scandeval/model_loading.py", line 50, in load_model
    tokenizer, model = setup.load_model(
  File "/home/mgh/.local/lib/python3.10/site-packages/scandeval/model_setups/hf.py", line 423, in load_model
    model, tokenizer = align_model_and_tokenizer(
  File "/home/mgh/.local/lib/python3.10/site-packages/scandeval/model_setups/utils.py", line 163, in align_model_and_tokenizer
    model(dummy_inputs)
  File "/home/mgh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1348, in forward
    transformer_outputs = self.model(
  File "/home/mgh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1070, in forward
    layer_outputs = decoder_layer(
  File "/home/mgh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 798, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/mgh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 494, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/mgh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mgh/.local/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
```

### Operating System

Linux

### Device

CUDA GPU

### Python version

3.10.x

### ScandEval version

11.0

**Comment by saattrupdan** [comment]
@mhenrichsen Can you try again with the newest version? (12.0.0)

**Comment by mhenrichsen** [comment]
I'll give it a go once the other model is done evaluating.

**Comment by saattrupdan** [comment]
@mhenrichsen Is this still happening with the newest version of ScandEval? Because if not then I'd like to close this issue.

**Comment by saattrupdan** [comment]
Closing due to inactivity. Feel free to re-open if this problem persists.
