### ISSUE TITLE
[BUG] ValueError: Could not find a benchmark class for any of the following potential names

### ISSUE THREAD

**Issue by BramVanroy** [ScandEval/ScandEval#408]
### 🐛 Describe the bug

Installed following requirements.txt in fresh env

```
flash-attn==2.5.7
scandeval[generative]==12.6.1
torch==2.1.2
wheel==0.43.0
```

Running

```
scandeval --model microsoft/phi-2 --language nl --use-flash-attention --raise-errors --verbose
```

Output

```
2024-04-19 13:48:40 ⋅ Benchmarking microsoft/phi-2 on the truncated version of the Dutch sentiment classification dataset Dutch Social
Traceback (most recent call last):
  File "/home/ampere/vanroy/scandeval/.venv_watt/bin/scandeval", line 8, in <module>
    sys.exit(benchmark())
  File "/home/ampere/vanroy/scandeval/.venv_watt/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ampere/vanroy/scandeval/.venv_watt/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ampere/vanroy/scandeval/.venv_watt/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ampere/vanroy/scandeval/.venv_watt/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ampere/vanroy/scandeval/.venv_watt/lib/python3.10/site-packages/scandeval/cli.py", line 331, in benchmark
    benchmarker(model=models)
  File "/home/ampere/vanroy/scandeval/.venv_watt/lib/python3.10/site-packages/scandeval/benchmarker.py", line 742, in __call__
    return self.benchmark(*args, **kwargs)
  File "/home/ampere/vanroy/scandeval/.venv_watt/lib/python3.10/site-packages/scandeval/benchmarker.py", line 589, in benchmark
    record = self._benchmark_single(
  File "/home/ampere/vanroy/scandeval/.venv_watt/lib/python3.10/site-packages/scandeval/benchmarker.py", line 693, in _benchmark_single
    dataset = self.dataset_factory.build_dataset(dataset_config)
  File "/home/ampere/vanroy/scandeval/.venv_watt/lib/python3.10/site-packages/scandeval/dataset_factory.py", line 57, in build_dataset
    raise ValueError(
ValueError: Could not find a benchmark class for any of the following potential names: dutch-social, sentiment-classification, sequence-classification.
```

I also tried the same for English, which lead to similar errors. I also downgraded to 12.6.0 which had the same error.

### Operating System

Linux

### Device

CUDA GPU

### Python version

3.10.x

### ScandEval version

12.6.1

**Comment by saattrupdan** [comment]
Thanks for your bug report. Can you try installing from source (main branch) and seeing if the issue persists?

**Comment by BramVanroy** [comment]
Yes, that does seem to work. Any idea why that is the case? Import-hell?

**Comment by saattrupdan** [comment]
Yeah it was just a stupid `openai` import statement that I forgot to wrap in a "only import if `openai` is installed" block 🙂 

Releasing the fix in an official version soon!

**Comment by BramVanroy** [comment]
Thanks for the quick fix!
