### ISSUE TITLE
[BUG] Can't load configuration

### ISSUE THREAD

**Issue by mMabeck** [ScandEval/ScandEval#422]
### 🐛 Describe the bug

Fresh scandeval[all] venv install. Won't load any models and I don't have any folders named it.

```
$ scandeval --model meta-llama/Meta-Llama-3-8B-Instruct 
2024-04-26 09:03:56 ⋅ Benchmarking meta-llama/Meta-Llama-3-8B-Instruct on the truncated version of the Swedish sentiment classification dataset SweReC
2024-04-26 09:04:05 ⋅ Loading model and tokenizer...
2024-04-26 09:04:05 ⋅ Couldn't load model config for 'meta-llama/Meta-Llama-3-8B-Instruct'. The error was OSError("Can't load the configuration of 'meta-llama/Meta-Llama-3-8B-Instruct'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'meta-llama/Meta-Llama-3-8B-Instruct' is the correct path to a directory containing a config.json file"). Skipping
```

### Operating System

Linux

### Device

CUDA GPU

### Python version

3.10.x

### ScandEval version

12.6.1

**Comment by saattrupdan** [comment]
Can you try running it again with the --verbose and --raise-errors flags?

**Comment by mMabeck** [comment]
Thanks, seems like a restart helped 😅 
For some reason my system can't find bitsandbytes==0.43 so I can't install 12.8.
I've also been getting this error for a long time, (which seems weird as it should use fp16 automatically):
```
ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla V100-SXM2-32GB GPU has compute capability 7.0. You can use float16 instead by explicitly setting the`dtype` flag in CLI, for example: --dtype=half.
```

I've just forced the HF implementation (only happens with vLLM), but perhaps add a flag to choose HF or fix the issue?

**Comment by saattrupdan** [comment]
Interesting, thanks! Can you send the full traceback?

**Comment by saattrupdan** [comment]
Ah, seems like your vLLM version is not up to date. Can you run `pip install -U scandeval[generative]` and try again? Alternatively, if that doesn't work (in which case, please send me that traceback too), then `pip install -U vllm`. Should be at least v0.4.0.

**Comment by mMabeck** [comment]
Thanks. Updating scandeval didn't seem to work
```
2024-04-26 17:02:26 ⋅ Benchmarking Mabeck/Danish-llama-3 on the truncated version of the Danish knowledge dataset Danske Talemåder
2024-04-26 17:02:39 ⋅ Loading model and tokenizer...
config.json: 100%|█████████████████████████████████████████████████████████████████████| 734/734 [00:00<00:00, 3.06MB/s]
Traceback (most recent call last):
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/vllm_models.py", line 136, in __init__
    self._model = LLM(**vllm_kwargs)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 91, in __init__
    engine_args = EngineArgs(
TypeError: EngineArgs.__init__() got an unexpected keyword argument 'max_logprobs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zhome/55/8/206247/scandenv/bin/scandeval", line 8, in <module>
    sys.exit(benchmark())
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/cli.py", line 331, in benchmark
    benchmarker(model=models)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 742, in __call__
    return self.benchmark(*args, **kwargs)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 589, in benchmark
    record = self._benchmark_single(
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 694, in _benchmark_single
    results, metadata_dict = dataset(model_id)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/benchmark_dataset.py", line 580, in __call__
    return self.benchmark(*args, **kwargs)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/benchmark_dataset.py", line 133, in benchmark
    tokenizer, model = load_model(
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/model_loading.py", line 52, in load_model
    tokenizer, model = setup.load_model(
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/model_setups/hf.py", line 315, in load_model
    raise e
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/model_setups/hf.py", line 300, in load_model
    model = VLLMModel(
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/vllm_models.py", line 140, in __init__
    self._model = LLM(**vllm_kwargs)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 109, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 391, in from_engine_args
    engine = cls(*engine_configs,
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 128, in __init__
    self._init_workers()
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 180, in _init_workers
    self._run_workers("init_model")
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 1041, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/vllm/worker/worker.py", line 87, in init_model
    _check_if_gpu_supports_dtype(self.model_config.dtype)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/vllm/worker/worker.py", line 300, in _check_if_gpu_supports_dtype
    raise ValueError(
ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla V100-SXM2-32GB GPU has compute capability 7.0. You can use float16 instead by explicitly setting the`dtype` flag in CLI, for example: --dtype=half.
```

Updating vllm to 0.4 got a new error (which I've also seen before):
```
024-04-26 17:09:27 ⋅ Benchmarking Mabeck/Danish-llama-3 on the truncated version of the Swedish sentiment classification dataset SweReC
Traceback (most recent call last):
  File "/zhome/55/8/206247/scandenv/bin/scandeval", line 8, in <module>
    sys.exit(benchmark())
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/cli.py", line 331, in benchmark
    benchmarker(model=models)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 742, in __call__
    return self.benchmark(*args, **kwargs)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 589, in benchmark
    record = self._benchmark_single(
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 693, in _benchmark_single
    dataset = self.dataset_factory.build_dataset(dataset_config)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/dataset_factory.py", line 57, in build_dataset
    raise ValueError(
ValueError: Could not find a benchmark class for any of the following potential names: swerec, sentiment-classification, sequence-classification.
```

**Comment by saattrupdan** [comment]
Thanks for that. Can you send me the following:

- Your ScandEval version
- Your vLLM version
- Your Python version
- The output if you set the --verbose flag, without the --raise-errors flag

**Comment by saattrupdan** [comment]
Also, when you updated ScandEval, you included the [generative] bit as well, right? Since vLLM should have been updated when you did that as well - seems a bit odd that it didn't.

**Comment by mMabeck** [comment]
Yes I did include it but I can only seem to install ScandEval=v12.6.1. 
I think the reason might be that I can't install bitsandbytes higher than 0.42:
```
$ python3 -m pip install bitsandbytes==0.43.1
ERROR: Could not find a version that satisfies the requirement bitsandbytes==0.43.1 (from versions: 0.31.8, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.34.0, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.35.4, 0.36.0, 0.36.0.post1, 0.36.0.post2, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.0.post1, 0.38.0.post2, 0.38.1, 0.39.0, 0.39.1, 0.40.0, 0.40.0.post1, 0.40.0.post2, 0.40.0.post3, 0.40.0.post4, 0.40.1, 0.40.1.post1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.41.2.post1, 0.41.2.post2, 0.41.3, 0.41.3.post1, 0.41.3.post2, 0.42.0)
ERROR: No matching distribution found for bitsandbytes==0.43.1
```

- ScandEval==12.6.1
- vLLM==0.4.1
- python==3.10.13
- torch==2.2.1

```
$ scandeval --model Mabeck/Danish-llama-3 --verbose 
2024-04-26 17:35:07 ⋅ Flash attention has not been installed, so this will not be used. To install it, run `pip install -U wheel && FLASH_ATTENTION_SKIP_CUDA_BUILD=TRUE pip install flash-attn --no-build-isolation`. Alternatively, you can disable this message by setting the flag ``--no-use-flash-attention`.
2024-04-26 17:35:07 ⋅ Benchmarking Mabeck/Danish-llama-3 on the truncated version of the Swedish sentiment classification dataset SweReC
Traceback (most recent call last):
  File "/zhome/55/8/206247/scandenv/bin/scandeval", line 8, in <module>
    sys.exit(benchmark())
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/cli.py", line 331, in benchmark
    benchmarker(model=models)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 742, in __call__
    return self.benchmark(*args, **kwargs)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 589, in benchmark
    record = self._benchmark_single(
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 693, in _benchmark_single
    dataset = self.dataset_factory.build_dataset(dataset_config)
  File "/zhome/55/8/206247/scandenv/lib/python3.10/site-packages/scandeval/dataset_factory.py", line 57, in build_dataset
    raise ValueError(
ValueError: Could not find a benchmark class for any of the following potential names: swerec, sentiment-classification, sequence-classification.
```

**Comment by saattrupdan** [comment]
And try installing vLLM v0.4.0, not 0.4.1. This was fixed in the newest scandeval version, but since you can't install that then try this directly.

**Comment by mMabeck** [comment]
Sure. Installing v0.4.0 didn't work and returns same error.

```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Scientific
Description:	Scientific Linux release 7.9 (Nitrogen)
Release:	7.9
Codename:	Nitrogen
```

**Comment by saattrupdan** [comment]
Can you try to run `pip install -U pip wheel && pip install --index-url https://pypi.org/simple -U scandeval[generative]`?

**Comment by mMabeck** [comment]
I ran it but can't update my pip due to server restrictions and currently using 23.3.1.

It continues to try in HF implementation after, so the bug is not a big deal:

```
$ scandeval --model Mabeck/Danish-llama-3 --verbose  --force 
2024-04-26 19:43:33 ⋅ Flash attention has not been installed, so this will not be used. To install it, run `pip install -U wheel && FLASH_ATTENTION_SKIP_CUDA_BUILD=TRUE pip install flash-attn --no-build-isolation`. Alternatively, you can disable this message by setting the flag ``--no-use-flash-attention`.
2024-04-26 19:43:33 ⋅ Benchmarking Mabeck/Danish-llama-3 on the truncated version of the Swedish sentiment classification dataset SweReC
2024-04-26 19:43:41 ⋅ Loading model and tokenizer...
2024-04-26 19:43:42 ⋅ Failed to benchmark with vLLM - trying with the Hugging Face implementation instead. The error raised was ValueError('Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla V100-SXM2-32GB GPU has compute capability 7.0. You can use float16 instead by explicitly setting the`dtype` flag in CLI, for example: --dtype=half.')
```

**Comment by saattrupdan** [comment]
Ah, so it's working now?

And if you can get vLLM working (i.e., get your pip upgraded) then that's like 5x faster and more accurate. You could look into just upgrading pip inside a virtual environment, or host installing it as a user install.

**Comment by mMabeck** [comment]
I will try that. And thanks a lot for the help!
