### ISSUE TITLE
[BUG] MobileLLM* models

### ISSUE THREAD

**Issue by Mikeriess** [ScandEval/ScandEval#595]
### 🐛 Describe the bug

Getting the following error when trying to benchmark the MobileLLM models:

```
2024-11-15 16:19:12 ⋅ Benchmarking facebook/MobileLLM-125M on the truncated version of the Swedish sentiment classification dataset SweReC

Downloading builder script:   0%|          | 0.00/6.60k [00:00<?, ?B/s]
Downloading builder script: 100%|██████████| 6.60k/6.60k [00:00<00:00, 12.1MB/s]

Downloading builder script:   0%|          | 0.00/6.77k [00:00<?, ?B/s]
Downloading builder script: 100%|██████████| 6.77k/6.77k [00:00<00:00, 13.1MB/s]
2024-11-15 16:19:19 ⋅ Loading model and tokenizer...
Traceback (most recent call last):
  File "/usr/local/bin/scandeval", line 8, in <module>
    sys.exit(benchmark())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/scandeval/cli.py", line 342, in benchmark
    benchmarker(model=models)
  File "/usr/local/lib/python3.10/dist-packages/scandeval/benchmarker.py", line 781, in __call__
    return self.benchmark(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/scandeval/benchmarker.py", line 597, in benchmark
    benchmark_output = self._benchmark_single(
  File "/usr/local/lib/python3.10/dist-packages/scandeval/benchmarker.py", line 731, in _benchmark_single
    results, metadata_dict, model, tokenizer = dataset(
  File "/usr/local/lib/python3.10/dist-packages/scandeval/benchmark_dataset.py", line 617, in __call__
    return self.benchmark(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/scandeval/benchmark_dataset.py", line 145, in benchmark
    model, tokenizer = load_model(
  File "/usr/local/lib/python3.10/dist-packages/scandeval/model_loading.py", line 52, in load_model
    model, tokenizer = setup.load_model(
  File "/usr/local/lib/python3.10/dist-packages/scandeval/model_setups/hf.py", line 310, in load_model
    model = VLLMModel(
  File "/usr/local/lib/python3.10/dist-packages/scandeval/vllm_models.py", line 133, in __init__
    self._model = self._initialise(vllm_kwargs=vllm_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/scandeval/vllm_models.py", line 146, in _initialise
    model = LLM(**vllm_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py", line 178, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 550, in from_engine_args
    engine = cls(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 291, in __init__
    self.tokenizer = self._init_tokenizer()
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 594, in _init_tokenizer
    return init_tokenizer_from_configs(
  File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/tokenizer_group/__init__.py", line 28, in init_tokenizer_from_configs
    return get_tokenizer_group(parallel_config.tokenizer_pool_config,
  File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/tokenizer_group/__init__.py", line 49, in get_tokenizer_group
    return tokenizer_cls.from_config(tokenizer_pool_config, **init_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py", line 30, in from_config
    return cls(**init_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py", line 23, in __init__
    self.tokenizer = get_tokenizer(self.tokenizer_id, **tokenizer_config)
  File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/tokenizer.py", line 120, in get_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 897, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2271, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2505, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama_fast.py", line 173, in __init__
    self.update_post_processor()
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama_fast.py", line 186, in update_post_processor
    bos_token_id = self.bos_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1187, in bos_token_id
    return self.convert_tokens_to_ids(self.bos_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id

.................. this pattern repeats itself

  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1072, in unk_token
    return str(self._unk_token)
RecursionError: maximum recursion depth exceeded while getting the str of an object

```

### Operating System

Linux

### Device

CUDA GPU

### Python version

3.10.x

### ScandEval version

13.0.0 (docker img)

**Comment by saattrupdan** [comment]
This seems to be due to Facebook's own custom code in [their repo](https://huggingface.co/facebook/MobileLLM-350M/blob/main/modeling_mobilellm.py). I'm closing the MobileLLM issues for now - they can be reopened when the implementation has been properly included in `transformers`.
